# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MixCoder',
                'doc_host': 'https://sofeikov.github.io',
                'git_url': 'https://github.com/sofeikov/MixCoder',
                'lib_path': 'MixCoder'},
  'syms': {'MixCoder.core': {'MixCoder.core.foo': ('core.html#foo', 'MixCoder/core.py')}}}
